// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP2XwzRZuVC9eULFLgP4qgNsnJb_m15uQ',
    appId: '1:560375027073:web:690a38729f64f5430b8480',
    messagingSenderId: '560375027073',
    projectId: 'temp-c52b5',
    authDomain: 'temp-c52b5.firebaseapp.com',
    storageBucket: 'temp-c52b5.firebasestorage.app',
    measurementId: 'G-STPBE3F6ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYWMpumJTetTbf_riOKeYv50ZnSLGMcyM',
    appId: '1:560375027073:android:951de94ff2a3ec2a0b8480',
    messagingSenderId: '560375027073',
    projectId: 'temp-c52b5',
    storageBucket: 'temp-c52b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKPCMXg81U3Q7pgypTQ7dnECzzIpgX-ow',
    appId: '1:560375027073:ios:091ddc942485c9db0b8480',
    messagingSenderId: '560375027073',
    projectId: 'temp-c52b5',
    storageBucket: 'temp-c52b5.firebasestorage.app',
    iosBundleId: 'com.example.geobullTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKPCMXg81U3Q7pgypTQ7dnECzzIpgX-ow',
    appId: '1:560375027073:ios:091ddc942485c9db0b8480',
    messagingSenderId: '560375027073',
    projectId: 'temp-c52b5',
    storageBucket: 'temp-c52b5.firebasestorage.app',
    iosBundleId: 'com.example.geobullTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP2XwzRZuVC9eULFLgP4qgNsnJb_m15uQ',
    appId: '1:560375027073:web:309085dde590e9080b8480',
    messagingSenderId: '560375027073',
    projectId: 'temp-c52b5',
    authDomain: 'temp-c52b5.firebaseapp.com',
    storageBucket: 'temp-c52b5.firebasestorage.app',
    measurementId: 'G-NSX5GC32HH',
  );
}
